apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  NODE_ENV: 'production'
  PORT: '3000'
  DATABASE_URL: 'postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)'
  CORS_ORIGIN: 'https://marketing-saas.pankajpandey.dev'
