apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  NODE_ENV: 'production'
  PORT: '3000'
  DATABASE_URL: 'postgresql://marketing_saas:super_secret_password@postgres:5432/marketing_saas'
  CORS_ORIGIN: 'https://marketing-saas.pankajpandey.dev' # ... rest of your ingress configuration
  NEXT_PUBLIC_API_URL: 'https://marketing-saas.pankajpandey.dev/api'
