apiVersion: batch/v1
kind: Job
metadata:
  name: database-migrations
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: migrations
          image: pank1999/marketing-saas-backend:7783b6c6ae4b533a72e55038b55900a0357dbdca
          command: ['npx', 'prisma', 'migrate', 'deploy']
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
      restartPolicy: Never
      imagePullSecrets:
        - name: my-docker-secret
