apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: 'bWFya2V0aW5nX3NhYXM=' # marketing_saas
  POSTGRES_PASSWORD: 'c3VwZXJfc2VjcmV0X3Bhc3N3b3Jk' # super_secret_password
  POSTGRES_DB: 'bWFya2V0aW5nX3NhYXM=' # marketing_saas
