---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # Let's Encrypt production API
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address for expiration notifications
    email: pankajpandey9589@gmail.com
    privateKeySecretRef:
      # Secret to store the ACME account private key
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
