apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  NODE_ENV: 'production'
  NEXT_PUBLIC_API_URL: 'https://marketing-saas.pankajpandey.dev/api'
  NEXT_PUBLIC_APP_URL: 'https://marketing-saas.pankajpandey.dev'
