apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Backend
  - backend/backend-config.yaml
  - backend/backend-secret.yaml
  - backend/backend-deployment.yaml
  - backend/backend-service.yaml
  - backend/backend-hpa.yaml
  - backend/migrations-job.yaml

  # Frontend
  - frontend/frontend-config.yaml
  - frontend/frontend-deployment.yaml
  - frontend/frontend-service.yaml

  # Ingress
  - ingress.yaml
