apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Database
  - database/postgres-secret.yaml
  - database/postgres-deployment.yaml
  - database/postgres-service.yaml

  # Cert Manager
  - cert-manager/cluster-issuer.yaml
